In [3]:
#placehold
import tensorflow as tf
data1 = tf.compat.v1.placeholder(tf.float32)
data2 = tf.compat.v1.placeholder(tf.float32)
dataAdd = tf.add(data1,data2)
print(dataAdd)
# print(dataAdd,feed_dict={data1:6,data2:2})
    # 1 dataAdd 2 data (feed_dict = {1:6,2:2})
print('end!')

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [4]:
#类比 数组 M行N列 []   内部[]  [里面 列数据]   [] 中括号整体 行数
#[[6,6]] [[6,6]]
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                     [3,4],
                     [5,6]])
print(data4.shape)# 维度
print(data4) #打印整体
print(data4[0])# 打印某一行
print(data4[0,1])# 1 1  MN = 0 32 = M012 N01
print(data4[:,0])#MN 列

(3, 2)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


2026-07-03 18:20:43.897640: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2026-07-03 18:20:43.923011: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2026-07-03 18:20:43.923404: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2026-07-03 18:20:43.924290: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operation