# 梯度下降算法

In [11]:
import tensorflow as tf
import numpy as np
# 实例化SGD
opt = tf.keras.optimizers.SGD(learning_rate=0.1)
# 定义要更新的参数
var = tf.Variable(1.0)
# 定义损失函数
loss = lambda:(var**2)/2.0
# 计算损失梯度，并进行参数更新
opt.minimize(loss,[var])
# 参数更新结果
var.numpy()

0.9

# momentum

In [12]:
# 实例化
opt = tf.keras.optimizers.SGD(learning_rate=0.1,momentum=0.9)
# 定义要更新的参数
var = tf.Variable(1.0)
val0= var.value()
# 定义损失函数
loss = lambda:(var**2)/2.0
# 第一次更新
opt.minimize(loss,[var]).numpy()
val1 = var.value()
# 第二次更新
opt.minimize(loss,[var]).numpy()
val2 = var.value()

AttributeError: 'NoneType' object has no attribute 'numpy'

In [5]:
val0

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.9>

In [7]:
val2

<tf.Tensor: shape=(), dtype=float32, numpy=0.71999997>

In [9]:
val0-val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.100000024>

In [10]:
val1-val2

<tf.Tensor: shape=(), dtype=float32, numpy=0.18>

# adagrad

In [11]:
# 实例化
opt = tf.keras.optimizers.Adagrad(learning_rate=0.1,initial_accumulator_value=0.1,epsilon=1e-06)
# 定义要更新的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var]).numpy()

1

In [12]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.90465385>

# RMSprop

In [14]:
# 实例化
opt = tf.keras.optimizers.RMSprop(learning_rate=0.1,rho=0.1)
# 定义要更新的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var]).numpy()
var.numpy()

0.89459074

# Adam

In [15]:
# 实例化
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
# 定义要调整的参数
var = tf.Variable(1.0)
# 定义损失函数
def loss():
    return (var**2)/2.0
# 进行更新
opt.minimize(loss,[var])
# 显示结果
var.numpy()

0.90000033